language: node_js
node_js:
- 14
dist: xenial
sudo: false
addons:
  apt:
    sources:
    - sourceline: ppa:ubuntu-toolchain-r/test
    packages:
    - build-essential
before_install:
- echo ${TRAVIS_NODE_VERSION}
- eval "$(curl -sL https://raw.githubusercontent.com/travis-ci/gimme/master/gimme | bash)"
- go env
- go get github.com/golang/dep/cmd/dep
- go get github.com/tcnksm/ghr
- go get github.com/jteeuwen/go-bindata/...
- go get github.com/elazarl/go-bindata-assetfs/...
- export GOPATH=$HOME/gopath
- export PATH=$HOME/gopath/bin:$PATH
- mkdir -p $HOME/gopath/src/github.com/c3sr/mlmodelscope
- rsync -az ${TRAVIS_BUILD_DIR}/ $HOME/gopath/src/github.com/c3sr/mlmodelscope/
- export TRAVIS_BUILD_DIR=$HOME/gopath/src/github.com/c3sr/mlmodelscope
install:
- cd ${TRAVIS_BUILD_DIR}
- npm install
- npm run bundle
- dep ensure -v
- go build -tags=nogpu
script: true
env:
  global:
  - GIMME_GO_VERSION=1.12
  - CGO_ENABLED=0
