variables:
  isMain: $[eq(variables['Build.SourceBranch'], 'refs/heads/master')]

jobs:
  - job: Web
    timeoutInMinutes: 0
    steps:
      - script: docker login -u $(DOCKER_USERNAME) -p $(DOCKER_PASSWORD)
        condition: eq(variables.isMain, true)
      - script: cd dockerfiles && make docker_build_cpu
      - script: cd dockerfiles && push.sh docker_push_cpu
        condition: eq(variables.isMain, true)
