variables:
  isMain: $[eq(variables['Build.SourceBranch'], 'refs/heads/master')]

jobs:
  - job: Web
    timeoutInMinutes: 0
    steps:
      - bash: |
          $(isMain) && docker login -u $(DOCKER_USERNAME) -p $(DOCKER_PASSWORD)
          cd dockerfiles
          make docker_build_cpu
          $(isMain) && ./push.sh docker_push_cpu
