version: '3.3'

networks:
  monitor-net:
    driver: bridge

services:
  carml:
    image: carml/web:amd64
    ports:
    - 8088:8088
    links:
    - jaeger
    - consul
    - caffe2
    - caffe
    - mxnet
    depends_on:
    - jaeger
    - consul
    - caffe2
    - caffe
    - mxnet
    environment:
    - PORT=8088
    - TRACER_ENDPOINTS=zipkin:9411
    - REGISTRY_ENDPOINTS=consul:8500
    entrypoint: carml web -d -v
    volumes:
    - type: volume
      source: ~/data/carml
      target: /data/carml
    - type: volume
      source: $HOME
      target: /root
  store:
    image: minio/minio
    container_name: store
    ports:
    - 9000:9000
    command: server /export
    environment:
    - MINIO_ACCESS_KEY=AKIAIOSFODNN7EXAMPLE
    - MINIO_SECRET_KEY=wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY
    volumes:
    - ~/data/store:/export
    - ~/data/store:/root/.minio
  caffe2:
    image: carml/caffe2-agent:amd64-cpu-latest
    container_name: caffe2
    links:
    - jaeger
    - consul
    entrypoint: caffe2-agent -d -v -l
    volumes:
    - type: volume
      source: ~/data/carml
      target: /data/carml
    - type: volume
      source: $HOME
      target: /root
    environment:
    - TRACER_ENDPOINTS=jaeger:9411
    - REGISTRY_ENDPOINTS=consul:8500
    depends_on:
    - jaeger
    - consul
  caffe:
    image: carml/caffe-agent:amd64-cpu-latest
    container_name: caffe
    links:
    - jaeger
    - consul
    entrypoint: caffe-agent -d -v -l
    volumes:
    - type: volume
      source: ~/data/carml
      target: /data/carml
    - type: volume
      source: $HOME
      target: /root
    environment:
    - TRACER_ENDPOINTS=jaeger:9411
    - REGISTRY_ENDPOINTS=consul:8500
    depends_on:
    - jaeger
    - consul
  mxnet:
    image: carml/mxnet-agent:amd64-cpu-latest
    container_name: mxnet
    links:
    - jaeger
    - consul
    entrypoint: mxnet-agent -d -v -l
    volumes:
    - type: volume
      source: ~/data/carml
      target: /data/carml
    - type: volume
      source: $HOME
      target: /root
    environment:
    - TRACER_ENDPOINTS=jaeger:9411
    - REGISTRY_ENDPOINTS=consul:8500
    depends_on:
    - jaeger
    - consul
  jaeger:
    image: jaegertracing/all-in-one:latest
    container_name: jaeger
    environment:
    - COLLECTOR_ZIPKIN_HTTP_PORT=9411
    ports:
    - 9411:9411
  consul:
    image: consul
    container_name: consul
    ports:
    - 8500:8500
    logging:
      driver: "none"
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - ./config/prometheus/:/etc/prometheus/
      - ~/data/carml/prometheus_data:/prometheus
    command:
      - '-config.file=/etc/prometheus/prometheus.yml'
      - '-storage.local.path=/prometheus'
      - '-alertmanager.url=http://alertmanager:9093'
      - '-storage.local.memory-chunks=100000'
    restart: unless-stopped
    expose:
      - 9090
    ports:
      - 9090:9090
    networks:
      - monitor-net
    labels:
      org.label-schema.group: "monitoring"

  nodeexporter:
    image: prom/node-exporter
    container_name: nodeexporter
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '-collector.procfs=/host/proc'
      - '-collector.sysfs=/host/sys'
      - '-collector.filesystem.ignored-mount-points=^/(sys|proc|dev|host|etc)($$|/)'
    restart: unless-stopped
    expose:
      - 9100
    networks:
      - monitor-net
    labels:
      org.label-schema.group: "monitoring"
  alertmanager:
    image: prom/alertmanager
    container_name: alertmanager
    volumes:
      - ./config/alertmanager/:/etc/alertmanager/
    command:
      - '-config.file=/etc/alertmanager/config.yml'
      - '-storage.path=/alertmanager'
    restart: unless-stopped
    expose:
      - 9093
    ports:
      - 9093:9093
    networks:
      - monitor-net
    labels:
      org.label-schema.group: "monitoring"

  cadvisor:
    image: google/cadvisor:v0.26.1
    container_name: cadvisor
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    restart: unless-stopped
    expose:
      - 8080
    networks:
      - monitor-net
    labels:
      org.label-schema.group: "monitoring"
  grafana:
    image: grafana/grafana
    container_name: grafana
    volumes:
      - ~/data/carml/grafana_data:/var/lib/grafana
    environment:
    - GF_SECURITY_ADMIN_USER=admin
    - GF_SECURITY_ADMIN_PASSWORD=admin
    - GF_USERS_ALLOW_SIGN_UP=false
    restart: unless-stopped
    expose:
      - 6000
    networks:
      - monitor-net
    ports:
      - 6000:3000
    labels:
      org.label-schema.group: "monitoring"
