version: '3.3'

services:
  carml:
    image: carml/web:amd64
    ports:
    - 8088:8088
    links:
    - jaeger
    - consul
    - caffe2
    - caffe
    - mxnet
    depends_on:
    - jaeger
    - consul
    - caffe2
    - caffe
    - mxnet
    environment:
    - PORT=8088
    - TRACER_ENDPOINTS=zipkin:9411
    - REGISTRY_ENDPOINTS=consul:8500
    entrypoint: carml web -d -v
    volumes:
    - type: volume
      source: ~/data/carml
      target: /data/carml
    - type: volume
      source: $HOME
      target: /root
  jaeger:
    image: jaegertracing/all-in-one:latest
    container_name: jaeger
    environment:
    - COLLECTOR_ZIPKIN_HTTP_PORT=9411
    ports:
    - 9411:9411
  consul:
    image: consul
    container_name: consul
    ports:
    - 8500:8500
  # store:
  #   image: minio/minio
  #   container_name: store
  #   ports:
  #   - 9000:9000
  #   command: server /export
  #   environment:
  #   - MINIO_ACCESS_KEY=AKIAIOSFODNN7EXAMPLE
  #   - MINIO_SECRET_KEY=wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY
  #   volumes:
  #   - ~/data/store:/export
  #   - ~/data/store:/root/.minio
  caffe2:
    image: carml/caffe2-agent:amd64-cpu-latest
    container_name: caffe2
    links:
    - jaeger
    - consul
    entrypoint: caffe2-agent -d -v -l
    volumes:
    - type: volume
      source: ~/data/carml
      target: /data/carml
    - type: volume
      source: $HOME
      target: /root
    environment:
    - TRACER_ENDPOINTS=jaeger:9411
    - REGISTRY_ENDPOINTS=consul:8500
    depends_on:
    - jaeger
    - consul
  caffe:
    image: carml/caffe-agent:amd64-cpu-latest
    container_name: caffe
    links:
    - jaeger
    - consul
    entrypoint: caffe-agent -d -v -l
    volumes:
    - type: volume
      source: ~/data/carml
      target: /data/carml
    - type: volume
      source: $HOME
      target: /root
    environment:
    - TRACER_ENDPOINTS=jaeger:9411
    - REGISTRY_ENDPOINTS=consul:8500
    depends_on:
    - jaeger
    - consul
  mxnet:
    image: carml/mxnet-agent:amd64-cpu-latest
    container_name: mxnet
    links:
    - jaeger
    - consul
    entrypoint: mxnet-agent -d -v -l
    volumes:
    - type: volume
      source: ~/data/carml
      target: /data/carml
    - type: volume
      source: $HOME
      target: /root
    environment:
    - TRACER_ENDPOINTS=jaeger:9411
    - REGISTRY_ENDPOINTS=consul:8500
    depends_on:
    - jaeger
    - consul
