version: '3.3'

networks:
  monitor-net:
    driver: bridge
  logging-net:
    driver: bridge

# Volumes for persisting data, see https://docs.docker.com/engine/admin/volumes/volumes/
volumes:
  mongo_data:
    driver: local
  es_data:
    driver: local
  graylog_journal:
    driver: local

services:
  carml:
    image: carml/web:amd64
    container_name: carml
    ports:
    - 8088:8088
    links:
    - jaeger
    - consul
    - caffe2
    - caffe
    - mxnet
    depends_on:
    - jaeger
    - consul
    - caffe2
    - caffe
    - mxnet
    environment:
    - PORT=8088
    - TRACER_ENDPOINTS=zipkin:9411
    - REGISTRY_ENDPOINTS=consul:8500
    restart: unless-stopped
    entrypoint: carml web -d -v
    volumes:
    - type: volume
      source: ~/data/carml
      target: /data/carml
    - type: volume
      source: $HOME
      target: /root
  caffe2:
    image: carml/caffe2-agent:amd64-cpu-latest
    container_name: caffe2
    links:
    - jaeger
    - consul
    restart: unless-stopped
    entrypoint: caffe2-agent -d -v -l
    volumes:
    - type: volume
      source: ~/data/carml
      target: /data/carml
    - type: volume
      source: $HOME
      target: /root
    environment:
    - TRACER_ENDPOINTS=jaeger:9411
    - REGISTRY_ENDPOINTS=consul:8500
    depends_on:
    - jaeger
    - consul
  caffe:
    image: carml/caffe-agent:amd64-cpu-latest
    container_name: caffe
    links:
    - jaeger
    - consul
    restart: unless-stopped
    entrypoint: caffe-agent -d -v -l
    volumes:
    - type: volume
      source: ~/data/carml
      target: /data/carml
    - type: volume
      source: $HOME
      target: /root
    environment:
    - TRACER_ENDPOINTS=jaeger:9411
    - REGISTRY_ENDPOINTS=consul:8500
    depends_on:
    - jaeger
    - consul
  mxnet:
    image: carml/mxnet-agent:amd64-cpu-latest
    container_name: mxnet
    links:
    - jaeger
    - consul
    restart: unless-stopped
    entrypoint: mxnet-agent -d -v -l
    volumes:
    - type: volume
      source: ~/data/carml
      target: /data/carml
    - type: volume
      source: $HOME
      target: /root
    environment:
    - TRACER_ENDPOINTS=jaeger:9411
    - REGISTRY_ENDPOINTS=consul:8500
    depends_on:
    - jaeger
    - consul
  store:
    image: minio/minio
    container_name: store
    expose:
    - 9030
    ports:
    - 9030:9000
    command: server /export
    environment:
    - MINIO_ACCESS_KEY=AKIAIOSFODNN7EXAMPLE
    - MINIO_SECRET_KEY=wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY
    volumes:
    - ~/data/store:/export
    - ~/data/store:/root/.minio
  jaeger:
    image: jaegertracing/all-in-one:latest
    container_name: jaeger
    environment:
    - COLLECTOR_ZIPKIN_HTTP_PORT=9411
    ports:
    - 9411:9411
  consul:
    image: consul
    container_name: consul
    ports:
    - 8500:8500
    logging:
      driver: "none"
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - ./config/prometheus/:/etc/prometheus/
      - ~/data/carml/prometheus_data:/prometheus
    command:
      - '-config.file=/etc/prometheus/prometheus.yml'
      - '-storage.local.path=/prometheus'
      - '-alertmanager.url=http://alertmanager:9093'
      - '-storage.local.memory-chunks=100000'
    restart: unless-stopped
    expose:
      - 9090
    ports:
      - 9090:9090
    networks:
      - monitor-net
    labels:
      org.label-schema.group: "monitoring"

  nodeexporter:
    image: prom/node-exporter
    container_name: nodeexporter
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '-collector.procfs=/host/proc'
      - '-collector.sysfs=/host/sys'
      - '-collector.filesystem.ignored-mount-points=^/(sys|proc|dev|host|etc)($$|/)'
    restart: unless-stopped
    expose:
      - 9100
    networks:
      - monitor-net
    labels:
      org.label-schema.group: "monitoring"
  alertmanager:
    image: prom/alertmanager
    container_name: alertmanager
    volumes:
      - ./config/alertmanager/:/etc/alertmanager/
    command:
      - '-config.file=/etc/alertmanager/config.yml'
      - '-storage.path=/alertmanager'
    restart: unless-stopped
    expose:
      - 9093
    ports:
      - 9093:9093
    networks:
      - monitor-net
    labels:
      org.label-schema.group: "monitoring"

  cadvisor:
    image: google/cadvisor:v0.26.1
    container_name: cadvisor
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    restart: unless-stopped
    expose:
      - 8080
    ports:
      - 8080:8080
    networks:
      - monitor-net
    labels:
      org.label-schema.group: "monitoring"
  grafana:
    image: grafana/grafana
    container_name: grafana
    volumes:
      - ~/data/carml/grafana_data:/var/lib/grafana
    environment:
    - GF_SECURITY_ADMIN_USER=admin
    - GF_SECURITY_ADMIN_PASSWORD=admin
    - GF_USERS_ALLOW_SIGN_UP=false
    restart: unless-stopped
    expose:
      - 3010
    networks:
      - monitor-net
    ports:
      - 3010:3000
    labels:
      org.label-schema.group: "monitoring"
  # MongoDB: https://hub.docker.com/_/mongo/
  mongo:
    image: mongo:3
    container_name: mongo
    volumes:
      - ~/data/carml/mongo_data:/data/db
    networks:
      - logging-net
  # Elasticsearch: https://www.elastic.co/guide/en/elasticsearch/reference/5.5/docker.html
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.5.2
    container_name: elasticsearch
    volumes:
      - ~/data/carml/es_data:/usr/share/elasticsearch/data
    environment:
      - http.host=0.0.0.0
      - transport.host=localhost
      - network.host=0.0.0.0
      # Disable X-Pack security: https://www.elastic.co/guide/en/elasticsearch/reference/5.5/security-settings.html#general-security-settings
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      mem_limit: 1g
    networks:
      - logging-net
  # Graylog: https://hub.docker.com/r/graylog/graylog/
  graylog:
    image: graylog/graylog:2.3
    container_name: graylog
    volumes:
      - ~/data/carml/graylog_journal:/usr/share/graylog/data/journal
      - ./config/graylog:/usr/share/graylog/data/config
    environment:
      # CHANGE ME!
      - GRAYLOG_PASSWORD_SECRET=somepasswordpepper
      # Password: admin
      - GRAYLOG_ROOT_PASSWORD_SHA2=8c6976e5b5410415bde908bd4dee15dfb167a9c873fc4bb8a81f6f2ab448a918
      - GRAYLOG_WEB_ENDPOINT_URI=http://127.0.0.1:9010/api
    links:
      - mongo
      - elasticsearch
    expose:
      - 9010
    ports:
      # Graylog web interface and REST API
      - 9010:9000
      # Syslog TCP
      - 514:514
      # Syslog UDP
      - 514:514/udp
      # GELF TCP
      - 12201:12201
      # GELF UDP
      - 12201:12201/udp
    networks:
      - logging-net
