# Gopkg.toml example
#
# Refer to https://golang.github.io/dep/docs/Gopkg.toml.html
# for detailed Gopkg.toml documentation.
#
# required = ["github.com/user/thing/cmd/thing"]
# ignored = ["github.com/user/project/pkgX", "bitbucket.org/user/project/pkgA/pkgY"]
#
# [[constraint]]
#   name = "github.com/user/project"
#   version = "1.0.0"
#
# [[constraint]]
#   name = "github.com/user/project2"
#   branch = "dev"
#   source = "github.com/myfork/project2"
#
# [[override]]
#   name = "github.com/x/y"
#   version = "2.4.0"
#
# [prune]
#   non-go = false
#   go-tests = true
#   unused-packages = true

[[override]]
  name = "github.com/c3sr/config"
  version = "0.1.0"

[[override]]
  name = "github.com/c3sr/dlframework"
  version = "0.3.9"

[[override]]
  name = "github.com/c3sr/grpc"
  version = "0.1.0"

[[override]]
  name = "github.com/c3sr/libkv"
  version = "0.3.1"

[[override]]
  name = "github.com/c3sr/logger"
  version = "0.1.0"

[[override]]
  name = "github.com/c3sr/machine"
  version = "0.1.0"

[[override]]
  name = "github.com/c3sr/nvidia-smi"
  version = "0.1.0"

[[override]]
  name = "github.com/c3sr/nvml-go"
  version = "0.2.0"

[[override]]
  name = "github.com/c3sr/parallel"
  version = "0.1.0"

[[override]]
  name = "github.com/c3sr/registry"
  version = "0.1.0"

[[override]]
  name = "github.com/c3sr/serializer"
  version = "0.1.0"

[[override]]
  name = "github.com/c3sr/store"
  version = "0.1.0"

[[override]]
  name = "github.com/c3sr/tegra"
  version = "0.1.0"

[[override]]
  name = "github.com/c3sr/tracer"
  version = "0.3.0"

[[override]]
  name = "github.com/c3sr/utils"
  version = "0.1.0"

[[override]]
  name = "github.com/c3sr/uuid"
  version = "0.1.0"

[[override]]
  name = "github.com/c3sr/vipertags"
  version = "0.1.0"

[[override]]
  name = "github.com/c3sr/web"
  version = "0.1.0"

[[override]]
  name = "github.com/labstack/echo"
  version = "3.3.10"

[[override]]
  name = "github.com/cenkalti/backoff"
  version = "=4.0.2"

[[override]]
  name = "github.com/stretchr/testify"
  version = "=1.6.1"

[prune]
  go-tests = true
  unused-packages = true
